jdbc:
  driver:
  url:
  username:
  password:
table:
  name:
  entity:
  alias:
  camel:
templates:
  - templateFile:
    templatePackage:
    fileName:
  - templateFile:
    templatePackage:
    fileName:
  - templateFile:
    templatePackage:
    fileName:
  - templateFile:
    templatePackage:
    fileName:
typeConvertList:
  int: Integer